// <auto-generated />
namespace ComedyClub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SeedComedyClub : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedComedyClub));
        
        string IMigrationMetadata.Id
        {
            get { return "201606290430375_SeedComedyClub"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
